### ISSUE TITLE
Deprecated selector in `photon-syntax\index.less`

### ISSUE THREAD

**Issue by ssnyder** [MaximSokolov/photon-syntax#1]
In `photon-syntax\index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor,
:host` => `atom-text-editor,atom-text-editor`

* `atom-text-editor .cursor,
:host .cursor` => `atom-text-editor .cursor,atom-text-editor .cursor`

* `atom-text-editor .selection .region,
:host .selection .region` => `atom-text-editor .selection .region,atom-text-editor .selection .region`

* `atom-text-editor .line.cursor-line,
:host .line.cursor-line` => `atom-text-editor .line.cursor-line,atom-text-editor .line.cursor-line`

* `atom-text-editor .indent-guide,
:host .indent-guide` => `atom-text-editor .indent-guide,atom-text-editor .indent-guide`

* `atom-text-editor .invisible-character,
:host .invisible-character` => `atom-text-editor .invisible-character,atom-text-editor .invisible-character`

* `atom-text-editor .wrap-guide,
:host .wrap-guide` => `atom-text-editor .wrap-guide,atom-text-editor .wrap-guide`

* `atom-text-editor .search-results .marker .region,
:host .search-results .marker .region` => `atom-text-editor .search-results .syntax--marker .region,atom-text-editor .search-results .syntax--marker .region`

* `atom-text-editor .search-results .marker.current-result .region,
:host .search-results .marker.current-result .region` => `atom-text-editor .search-results .syntax--marker.current-result .region,atom-text-editor .search-results .syntax--marker.current-result .region`

* `atom-text-editor .gutter .line-number,
:host .gutter .line-number` => `atom-text-editor .gutter .line-number,atom-text-editor .gutter .line-number`

* `atom-text-editor .gutter .line-number.cursor-line,
:host .gutter .line-number.cursor-line,
atom-text-editor .gutter .line-number.cursor-line-no-selection,
:host .gutter .line-number.cursor-line-no-selection` => `atom-text-editor .gutter .line-number.cursor-line,atom-text-editor .gutter .line-number.cursor-line,
atom-text-editor .gutter .line-number.cursor-line-no-selection,atom-text-editor .gutter .line-number.cursor-line-no-selection`

* `atom-text-editor .gutter .line-number.folded,
:host .gutter .line-number.folded` => `atom-text-editor .gutter .line-number.folded,atom-text-editor .gutter .line-number.folded`

* `atom-text-editor .gutter .git-line-added.cursor-line,
:host .gutter .git-line-added.cursor-line` => `atom-text-editor .gutter .git-line-added.cursor-line,atom-text-editor .gutter .git-line-added.cursor-line`

* `atom-text-editor .gutter .git-line-modified.cursor-line,
:host .gutter .git-line-modified.cursor-line` => `atom-text-editor .gutter .git-line-modified.cursor-line,atom-text-editor .gutter .git-line-modified.cursor-line`

* `.comment` => `.syntax--comment`

* `.string` => `.syntax--string`

* `.string.regexp` => `.syntax--string.syntax--regexp`

* `.string .punctuation.definition` => `.syntax--string .syntax--punctuation.syntax--definition`

* `.constant.numeric` => `.syntax--constant.syntax--numeric`

* `.constant.language` => `.syntax--constant.syntax--language`

* `.constant.character` => `.syntax--constant.syntax--character`

* `.variable.parameter` => `.syntax--variable.syntax--parameter`

* `.variable.language` => `.syntax--variable.syntax--language

**Comment by MaximSokolov** [comment]
Thanks for heads up! Should be fixed in v0.8.3
