### ISSUE TITLE
Deprecated selector in `photon-syntax/index.less`

### ISSUE THREAD

**Issue by leelandmiller** [MaximSokolov/photon-syntax#3]
In `photon-syntax/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.syntax--source.syntax--go .entity.name.import` => `.syntax--source.syntax--go .syntax--entity.syntax--name.syntax--import`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by MaximSokolov** [comment]
Thanks for the report! This must be fixed in v0.10.1
